management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
  port: 9000
  
spring:
  sql:
    init:
      platform: h2
      continue-on-error: false
      mode: always
  datasource:
    url: jdbc:h2:mem:customerdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: customer
    password: customer
    type: com.zaxxer.hikari.HikariDataSource # Default
    hikari:
      pool-name: customer-connection-pool
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 5 #maximum pool size
      connection-timeout: 1000 #maximum number of milliseconds that a client will wait for a connection
      idle-timeout: 1000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior.
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true #To defer schema(-<<Platform>>).sql & data(-<<Platform>>).sql execution after HB Schema and import.sql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        generate_statistics: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false
                
logging:
  file: logs/application-debug.log
  pattern:
    console: "%d{yyyy-MM-dd} | %d{HH:mm:ss.SSS} | %thread | %5p | %logger{25} | %m%n"
    file: "%d{yyyy-MM-dd} | %d{HH:mm:ss.SSS} | %thread | %5p | %logger{25} | %m%n"
  level:
    root: INFO
    com.learning.bank.customer.customerservice: INFO
    org.springframework: DEBUG
    org.hibernate: DEBUG