#Properties injecting from ENV variable created by Maven
service:
  name: @project.name@
  artifactId: @project.artifactId@
  version: @project.version@
  description: @project.description@
  java:
    version: @java.version@

server:
  port: 8081
  servlet:
    context-path: /customer

spring:
  profiles:
    active: @spring.profiles.active@
  jackson:
    date-format: dd-MM-yyyy
    serializatipon.indent-output: true
    default-property-inclusion: non_null
        
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: alpha
